image: Visual Studio 2019

build_script:
- cd solver_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target solver

deploy:
    provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    
    auth_token:
        secure: 8b64tpiq0n0kh1wqr46g
        
    artifact: /_build/*tar.gz
    
    force_update:true
    
    on:
        appveyor_repo_tag: true
