image: Visual Studio 2019

build_script:
- cd hello_world_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build _build --target hello_world
- ./hello_world
- cd ..
- cd solver_application
- cmake -H. -B_build
- cmake --build _build
- cmake --build -build --target solver
